### ISSUE TITLE
报警处于“活跃” ，”知悉“，”恢复“的切换

### ISSUE THREAD

**Issue by liuts** [TalkingData/owl#11]
报警处于“活跃” 状态，我点 “知悉”1小时，开始处理报警，5分钟内处理完成了， 报警的状态 不能变为“恢复”状态。一般处理流程是，收到微信报警，点击知晓不在继续报警，登录机器开始处理，处理完成以后，等恢复的微信。

**Comment by wuyingsong** [comment]
报警恢复后会自动重置状态

**Comment by liuts** [comment]
实际测试下，需要超过 知悉的1个小时后，才会变为“恢复”，在能够收到报警。我实际希望的是 在我处理完成就能够状态 变为恢复“恢复”。我是在 “报警事件” 选卡里看到一直是“知悉”。

**Comment by wuyingsong** [comment]
@liuts 我这边一直用都没遇到这种情况呢，你有更详细的信息可以提供吗？

**Comment by liuts** [comment]
可能和我的操作方式有关，我的操作步骤是：
1，设置报警规则，system.mem.free>0 报警，5分钟后报警发生，点击置为"知悉"状态
2，把报警规则改为system.mem.free<0 报警恢复，但是收不到微信通知

**Comment by wuyingsong** [comment]
system.mem.free 不可能小于 0 吧，报警怎么会恢复

**Comment by liuts** [comment]
不恢复的原因是：报警处于“活跃”状态，我把触发此报警的“策略”删除，所以报警变为永远不恢复的报警了
