### ISSUE TITLE
controller 入库bug

### ISSUE THREAD

**Issue by feijilei** [TalkingData/owl#2]
![image](https://cloud.githubusercontent.com/assets/1579421/21036282/d29d7a42-bdff-11e6-938c-7921c33aa740.png)
新增448行
![image](https://cloud.githubusercontent.com/assets/1579421/21036305/f1670c36-bdff-11e6-90bf-16cda3b42a08.png)

**Comment by wuyingsong** [comment]
重新确认了下，报错是sql mode导致的。
当时新报警没加ProcessTime是考虑新建的报警应该是没有处理时间的。


解决方案参考：http://stackoverflow.com/a/36374690

**Comment by feijilei** [comment]
这样也可以，安装手册里面可以备注下，不然后面使用的人安装好，发现报警是不WORK的

**Comment by wuyingsong** [comment]
我们会在代码里面也修复这个问题。
