### ISSUE TITLE
怎样使用微信报警功能？

### ISSUE THREAD

**Issue by sonwa** [TalkingData/owl#24]
请问怎样使用微信报警功能？

**Comment by wuyingsong** [comment]
@sonwa  目前没有支持微信告警，我们用的是企业微信。
使用的脚本是 controller/scripts/notifications/send_wechat.py 
打开企业微信 web 管理后台，创建一个自建应用，完成以后即可获得 AgentId和Secret
点击我的企业 -> 企业信息里面可以获取到企业ID(CORP_ID)
将 CORP_ID，SECRET，AGENT_ID 配置到 send_wechat.py 脚本中即可
