### ISSUE TITLE
该监控系统的架构是什么样的？有无文档？

### ISSUE THREAD

**Issue by a523** [TalkingData/owl#4]
对分布式监控系统感兴趣，看到这个项目，想知道是如何实现的，它的一个框架是怎样的？有无相关的文档可以参考？

**Comment by sunlizhe** [comment]
plz 加入492850035 ，群文件有相关的文档信息。 架构设计上类似于master client的架构。和大部分监控系统也比较类似。预警配置挺灵活，而且插件的方式可以方便收集服务的metrics信息。

**Comment by wuyingsong** [comment]
@a523 架构参考 https://github.com/TalkingData/owl/blob/master/arch.png ，安装部署的文档在我们的交流群中有共享。

**Comment by jasonTangxd** [comment]
插件怎么使用呢？不是很清楚，看代码是去读了plugins下面的文件，请问有具体说明吗？

**Comment by wuyingsong** [comment]
插件放在agent的plugins目录下，然后在管理页面->插件管理上填写对应的插件名称和参数，绑定到主机上即可，agent会定期去执行。

**Comment by jasonTangxd** [comment]
恩，谢谢！当时弄好，然后过来已经把这个问题删了的，不知道怎么还能回复。
